# Generated by Django 4.0.5 on 2022-06-13 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderProfile',
            fields=[
                ('User_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Birth', models.DateField()),
                ('Phone', models.CharField(max_length=12)),
                ('User_specialty', models.CharField(max_length=64)),
                ('User_field', models.CharField(max_length=64)),
                ('User_image', models.ImageField(blank=True, upload_to='')),
                ('Service', models.IntegerField(choices=[(1, 'Technical Advice'), (2, 'Technical Services'), (3, 'Technical Advice and Service')])),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_title', models.CharField(max_length=64)),
                ('Service_type', models.CharField(max_length=64)),
                ('Desc', models.TextField(max_length=200)),
                ('Service_time', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceProvider.serviceproviderprofile')),
            ],
        ),
    ]
