# Generated by Django 4.0.5 on 2022-06-15 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('user_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth', models.DateField()),
                ('phone', models.CharField(max_length=12)),
                ('user_image', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_title', models.CharField(max_length=64)),
                ('order_type', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(default='Waiting', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('comment', models.TextField(max_length=200)),
                ('rating', models.IntegerField(choices=[[1, 'Wonderful'], [2, 'Good'], [3, 'Acceptable']])),
                ('review_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
