# Generated by Django 4.0.5 on 2022-06-13 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('User_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Birth', models.DateField()),
                ('Phone', models.CharField(max_length=12)),
                ('User_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_title', models.CharField(max_length=64)),
                ('Order_type', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('Date_time', models.DateTimeField(auto_now_add=True)),
                ('Order_status', models.CharField(default='Waiting', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=64)),
                ('Comment', models.TextField(max_length=200)),
                ('Rating', models.IntegerField(choices=[[1, 'Wonderful'], [2, 'Good'], [3, 'Acceptable']])),
                ('Review_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
