# Generated by Django 4.0.5 on 2022-06-13 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('ServiceProvider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceProvider.serviceproviderprofile'),
        ),
        migrations.AddField(
            model_name='orders',
            name='Recipient_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceProvider.serviceproviderprofile'),
        ),
        migrations.AddField(
            model_name='orders',
            name='Sender_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.clientprofile'),
        ),
    ]
